@baseUrl = http://54.153.171.61:3000
@token = 

### Register New User
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "testuser",
    "email": "your-email@example.com",
    "password": "TestPassword123!"
}

### Confirm Registration (use code from email)
POST {{baseUrl}}/api/auth/confirm
Content-Type: application/json

{
    "username": "testuser",
    "code": "123456"
}

### Login with Cognito
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "username": "testuser",
    "password": "TestPassword123!"
}